### ISSUE TITLE
建议提供同时提供无压缩版单文件js

### ISSUE THREAD

**Issue by bin20060407** [kyo4311/jquery.qqface#1]
感谢无私奉献，建议同时提供无压缩版单文件，毕竟有时候可能会修改其中表情

**Comment by kyo4311** [comment]
感谢支持！如果你要改代码，可以试试下面的步骤：

第一步 把这外包下载到本地
git clone https://github.com/kyo4311/jquery.qqface.git

第二到 进入这个目录

第三步安装npm包，需要node环境
npm install 

第四步找到 webpack.config.js 下面的 new webpack.optimize.UglifyJsPlugin()这行注解

第五步 改代码

第六步 打包代码
gulp js

**Comment by bin20060407** [comment]
这个项目还在更新吗？做了一些调整，可否发起pull request
